### ISSUE TITLE
dbcp2 and atomikos jta 5.0.6 integration : There is no registered resource that can recover the given XAResource instance

### ISSUE THREAD

**Issue by hx78** [atomikos/transactions-essentials#108]
**Describe the bug**
we use atomikos jta 5.0.6 and dbcp2 datasource pool 2.7.0，how ever, it throw “There is no registered resource that can recover the given XAResource instance”

In addition we found ， atomikos 4.0.6 will create TemporaryXaTransatcionalResource to avoid this problem, why 5.0.6 doesn't take this way ? how can we solve this problem in 5.0.6?

**Comment by GuyPardon** [comment]
You should use our pools, not DBCP2. DBCP2 is not XA-capable. We used to "hide" this in 4.0 but it seemed safer to not do that any more in 5.0

**Comment by hx78** [comment]
what do you mean dbcp2 is not XA-capable?  just i konw dbcp2 support jta. we have project use  dbcp2 and narayana integration.

**Comment by hx78** [comment]
> You should use our pools, not DBCP2. DBCP2 is not XA-capable. We used to "hide" this in 4.0 but it seemed safer to not do that any more in 5.0

what do you mean dbcp2 is not XA-capable? just i konw dbcp2 support jta. we have project use dbcp2 and narayana integration.

**Comment by GuyPardon** [comment]
OK it looks like there are some XA interfaces in there, but we don't recover because there is no JdbcTransactionalResource registered. Maybe you can try to register one yourself, via Configuration.addResource?

**Comment by hx78** [comment]
> OK it looks like there are some XA interfaces in there, but we don't recover because there is no JdbcTransactionalResource registered. Maybe you can try to register one yourself, via Configuration.addResource?

I did it  and it is ok for mysql  but not gaussDB.  isSameRM method : xares == this in guassDB, so  it alway be  false.  so,  do you  have  any other idea for this?  tks

**Comment by GuyPardon** [comment]
Well worst case you can check if the xaresource classname is the same but you would only be able to add 1 such DBMS to your config.

**Comment by hx78** [comment]
> Well worst case you can check if the xaresource classname is the same but you would only be able to add 1 such DBMS to your config.

I can config atomikos to support such DBMS?

**Comment by hx78** [comment]
> Well worst case you can check if the xaresource classname is the same but you would only be able to add 1 such DBMS to your config.

Can I config atomikos to support such DBMS?

**Comment by GuyPardon** [comment]
Not currently. I don't know GaussDB really but I doubt you would have 2 instances for the same application?

**Comment by GuyPardon** [comment]
GaussDB seems like a Postgres fork so maybe you can try to connect with PGXADataSource?

**Comment by hx78** [comment]
> Not currently. I don't know GaussDB really but I doubt you would have 2 instances for the same application?

You can ignore this DB. I mean, you don't need to know this DB.

Yes, I have some instances for xaresoure, one from JdbcTransactionalResource and others from [XAResource ](https://github.com/apache/commons-dbcp/blob/master/src/main/java/org/apache/commons/dbcp2/managed/DataSourceXAConnectionFactory.java).

**Comment by hx78** [comment]
> GaussDB seems like a Postgres fork so maybe you can try to connect with PGXADataSource?

OK, tks very much
