### ISSUE TITLE
com.atomikos.icatch.RollbackException: prepare failed because one or more resources refused to commit

### ISSUE THREAD

**Issue by sarathccs** [atomikos/transactions-essentials#110]
**Describe the bug**
I have a jms connectivity to MQ. Used AtomikosConnectionFactory bean, spring CachingConnectionFactory and spring jmsTemplate. 
Spring version : 5.2.3 Release
Atomikos : 5.0.6

While the mq has no messages to drain i get rollback exception, i have given transaction timeout 300000 in atomikos and 30000 in jmstemplate. i can get rid of this exception if i change the jms template timeout to 10000 or below. but anythig above creates a rollback only participant and throwing error. since the atomikos user transaction timeout is much above jms template this erorr should not come but dont know why. 

Error has thrown from ActiveStateHandler.prepare(207)

Kindly assist to know what went wrong while jms time out is more than 10secs

**Comment by GuyPardon** [comment]
Sounds normal: if you want for so long that the transaction times out, you will get this if there is no message there.

I would try with the JMS template lower indeed.

**Comment by sarathccs** [comment]
My concern is why is it not throwing an exception if the jms timeout is lower than 10secs? and why is it throwing above it? given we still maintain atomikos timeout of 300 secs. lt looks like atomikos transaction is trying to commit before its timeout(300) and not before 10secs. Why that happens, on what condition? Could you please answer. 
We had not been getting this error with same setting with atomikos 3,x versioin

**Comment by GuyPardon** [comment]
Spring tries to commit even if there is no message.

So when there is no message available, your code will:

1. start a transaction
2. begin waiting for the jms timeout
3. try to commit the transaction

If the jms timeout is like the transaction timeout, then 3. will have race conditions with transaction timeout and you will get this error.

Solution: don't wait do long in the JMS timeout.

Best

**Comment by sarathccs** [comment]
Here jms timeout is 30secs and atomikos-jta timeout is 300 secs. How is spring tries to commit it before 30secs!?.

**Comment by GuyPardon** [comment]
I am not sure but we can look into more details if you are open to considering our commercial edition (ExtremeTransactions). We have a free trial where we can give you some more in-depth support.

Would that be an option?

**Comment by sarathccs** [comment]
The issue has been resolved by setting **com.atomikos.icatch.default_jta_timeout** to a bigger number. default was 10000ms. 

We have below timeout setting for atomikos
1.com.atomikos.icatch.max_timeout or setting it through UserTransaction/AtomikosTransactionManager's transactioinTimeout setup. 
Could u please clarify diff between setting above and the com.atomikos.icatch.default_jta_timeout parameter

Thanks

**Comment by GuyPardon** [comment]
The default is what is used when you create a transaction, but it is capped to max_timeout if you specify a larger value.

**Comment by sarathccs** [comment]
Thanks, that is clear about max timeout and default jta timeout

What happens while we set transactionTimeout withatomikos  UserTransactionManager/UserTransaction?. Is this setting default or max? or totally different? Because we see this setup suggested in docs available with atomikos sample download

Thanks

**Comment by GuyPardon** [comment]
Setting the timeout explicitly will override the default and still needs to be lower than max_timeout.

**Comment by sarathccs** [comment]
But with atomikos 5.0.6 setting timeout via UserTransaction being overridden by dfault_jta_timeout or the setup has no effect. That's why i got this issue. As per atomikos docs i was setting timeout via UserTransaction and failed.

**Comment by GuyPardon** [comment]
OK that may be one of the bugs we fixed in the commercial edition then...

**Comment by sarathccs** [comment]
Thanks for the clarifications.

Best
