### ISSUE TITLE
Recommendation for hibernate.connection_release_mode with atomikos

### ISSUE THREAD

**Issue by sbrown44** [atomikos/transactions-essentials#111]
Is there a recommendation for what setting to use for the hibernate property hibernate.connection_release_mode when used with atomikos jta and connection pool outside of a j2ee container.
There are two possibilities, after_statement and after_transaction. The default in a jta environment is after_statement, but I am noticing that because of the large number of statements we are running in our transactions, that the application is spending a lot of time trying to access the atomikos connection pool, and sometimes the connection is not staying bound to the transaction. Is there any downside to setting this to after_transaction, in which case hibernate keeps the connection for the duration of the transaction instead of going to atomikos on every statement call.
Atomikos 4.0.6, Hibernate 5.4.3, postgresql 9.6

**Comment by GuyPardon** [comment]
You may want to try with our 5.0 and check this page:

https://www.atomikos.com/Documentation/HibernateIntegration

Let me know if that helps

**Comment by sbrown44** [comment]
We are planning to upgrade atomikos to v 5. As we don't set anything right now, the default setting for hibernate is DELAYED_ACQUISITION_AND_RELEASE_AFTER_STATEMENT anyway.  I just did some trace logging and there are a large number (10^5) TransactionContexts that SessionHandleState has to iterate through to close a transaction - based on many log entries like this:
 - a SessionHandleState with 378678 context(s): delegating session close to a TransactionContext 
I am still looking at the logs and the code to try to understand how this could have developed.

**Comment by GuyPardon** [comment]
Looks like your code is caching connections?
