### ISSUE TITLE
org.hibernate.hql.spi.id.IdTableHelper - Unable to use jdbc connection to create statement

### ISSUE THREAD

**Issue by sarathccs** [atomikos/transactions-essentials#112]
I have a jms connectivity to MQ. Used AtomikosConnectionFactory and JDBC connectivity to Oracle using AtomikosDataSourceBean
Spring version : 5.2.3 Release
Hibernate version: 5.4.2.Final
Atomikos : 5.0.6

I get below error while start up of the application before the context get load.

org.hibernate.hql.spi.id.IdTableHelper - Unable to use jdbc connection to create statement
com.atomikos.jdbc.internal.AtomikosSQLException: A  JTA transaction is required but none was found - please start one first (or localTransactionMode = true to allow JDBC transactions)

I wont get this error if i add property localTransactionMode = true to AtomikosDataSourceBean. 
Below is my question:
Since i use spring @Transactional for all the transactions(including two phase) do i really need to set localTransactionMode = false to get xa capability? If so how can i get rid of this error?

Please be noted i am also using JMS AtomikosConnectionFactory with transacted true. 

Thanks
Sarath

**Comment by GuyPardon** [comment]
You are getting this error because you try to use our 5.0 JDBC without a JTA transaction, i.e. with JDBC-level commit on the connection. Typically this happens for initial table creation.

Check if you really want to do JDBC commits rather than JTA commits and set localTransactionMode=true if so.

**Comment by sarathccs** [comment]
Yes agreed. 
Since i use spring @transactional(jta) for all the transactions(including two phase) do i really need to set localTransactionMode = false in  AtomikosDataSourceBean to get xa capability?

**Comment by sarathccs** [comment]
Could you please clarify above doubt

**Comment by GuyPardon** [comment]
With JTA it should enlist in the transaction.

**Comment by sarathccs** [comment]
Thanks GuyPardon. Its clear now
