### ISSUE TITLE
Would like to know more about recovery process.

### ISSUE THREAD

**Issue by gimantha** [atomikos/transactions-essentials#118]
Hi all,

I am experimenting with atomikos to integrate it with ballerina(https://ballerina.io/). I have few questions regarding the recovery process of atomikos. I read in your documentation, that you are using your own version of momento pattern for transaction logging. I assume that when we use the atomikos transaction manager in our Java programs, it runs in the same java process. Say the whole java program crashes in the middle of a transaction (which makes the transaction manager also crashes). Then how does the transaction manager recover when we start the Java program again? Is that by looking at the transaction log? How does it recover if the java program crashes before transaction manager logs to the log file?

**Comment by GuyPardon** [comment]
Yes, we use the transaction log file if one is present.

Not sure why you are integrating with Ballerina, since it has its own transaction manager AFAIK?

**Comment by gimantha** [comment]
Hi @GuyPardon, 
Thank you replying.

Yes. Ballerina has its own transaction manager, but we are planning to rewrite it. Ballerina runtime is JVM based. So we thought of wrapping Atomikos transaction manager and use it, so that we don't have to worry about recovery of resource managers and transaction manager, as atomikos already handles them. I am trying to figure out the implications that can arise if the Ballerina runtime crashes (that means if the JVM crashes) when Atomikos transaction manager resides in the same JVM. Will Atomikos transaction manager recover If I restart the JVM after a crash in the middle of a transaction by looking at the transaction log it maintains?

**Comment by GuyPardon** [comment]
Yes, the transaction manager will recover. But you are probably looking at an old release, I would take 5.0 if I were you.

**Comment by gimantha** [comment]
Thank you @GuyPardon for the suggestion, I will take 5.0.
