### ISSUE TITLE
PooledAlarmTimer thread leak in out of disk space situation

### ISSUE THREAD

**Issue by bgK** [atomikos/transactions-essentials#130]
When the disk where the recovery log is stored is out of free space
(or writing otherwise fails) the PooledAlarmTimer threads created for
each transaction are not always cleaned up.

The sequence of events as I understand it is as follows:
1. A new transaction is started. `CoordinatorImp` creates a new `PooledAlarmTimer`
   thread.
2. Business code completes. The transaction tries to commit. Writing to the
   recovery log file generates a `LogWriteException`.
3. The exception propagates out of `StateRecoveryManagerImp` to
   `FSMImp#notifyListeners`. The other listeners are never called. That includes
   `CoordinatorImp` that would otherwise stop the `PooledAlarmTimer` thread.

The recovery thread fails to clean up the state as `CachedRepository` is 
`corrupt`ed. I understand that at this point the application is in a failed
state and must be restarted. However the creation of an unbounded amount of
threads has a significant impact on the host machine. In our case a number
of unrelated applications sharing the same host were brought down due to pid
limit exhaustion.

The thread leak does not fix itself once the underlying issue is resolved,
the `PooledAlarmTimer` threads stay indefinitely:
```sh
$ jstack 2763997 | grep "Atomikos:" | wc -l
196
```

This happens with Transaction Essentials 5.0.8.

**Comment by GuyPardon** [comment]
Thanks, looks like a bug so we'll have a look!

**Comment by GuyPardon** [comment]
This will be part of release 5.0.9 soon.
