### ISSUE TITLE
init SQL setting when creating new connection

### ISSUE THREAD

**Issue by podmak** [atomikos/transactions-essentials#132]
hi, 

Is it possible to set init SQL statement which will be executed every time new connection is created? I need to execute `ALTER SESSION SET NLS_SORT = 'SLOVAK'` for proper sorting in slovak language
I found similar thread in [old forum](https://fogbugz.atomikos.com/default9420.html)  without clear answer.

**Comment by GuyPardon** [comment]
Sorry for the late reply. We do have something like that in our commercial distribution but not as part of our open source.
