### ISSUE TITLE
List of major releases/changes

### ISSUE THREAD

**Issue by arasheed** [atomikos/transactions-essentials#133]
We are upgrading Atomikos from 3.8.0 to 5.0.8. And there has been numerous releases between those two versions. Is there a list of major releases ? I would like to know major changes (e.g. it does not generate epoch files no more) especially configuration changes. 

Thanks.

**Comment by GuyPardon** [comment]
Does this help?


https://www.atomikos.com/Blog/TransactionsEssentials4dot0dot0
https://www.atomikos.com/Blog/TransactionsEssentials5dot0

Regards

**Comment by arasheed** [comment]
Thank you. Very useful!
