### ISSUE TITLE
TransactionEssentials 4.0.0 ThreadLocal timeout value

### ISSUE THREAD

**Issue by batmanexe** [atomikos/transactions-essentials#138]
Hi,

Since TransactionEssentials 4.0.0, the timeout value on the UserTransactionImp bean gets loaded, but not used. Whenever a new transaction is created, it's using the default 10 seconds instead. Maybe my configuration is wrong or I'm missing something?

`	<bean id="AtomikosTransactionManager" class="com.atomikos.icatch.jta.UserTransactionManager" init-method="init" destroy-method="close">
		<property name="forceShutdown" value="true" />
	</bean>
	<bean id="AtomikosUserTransaction" class="com.atomikos.icatch.jta.UserTransactionImp">
		<property name="transactionTimeout" value="420" />
	</bean>
	<bean id="JtaTransactionManager" class="org.springframework.transaction.jta.JtaTransactionManager">
		<property name="transactionManager" ref="AtomikosTransactionManager" />
		<property name="userTransaction" ref="AtomikosUserTransaction" />
	</bean>
	<tx:annotation-driven transaction-manager="JtaTransactionManager"/>`

Datasource:

`	<bean id="dataSource" class="com.atomikos.jdbc.AtomikosDataSourceBean" init-method="init" destroy-method="close" >
		<property name="uniqueResourceName" value="dataSource"/>
		<property name="xaDataSourceClassName" value="${driver}"/>
		<property name="xaProperties">
			<props>
                <prop key="URL">${url}</prop>
	            <prop key="user">${user}</prop>
	            <prop key="password">${pass}</prop>
         	</props>
		</property>		
		<property name="minPoolSize" value="${minActive}"/>
		<property name="maxPoolSize" value="${maxActive}"/>		
		<property name="borrowConnectionTimeout" value="${maxWait}"/>
		<property name="maxIdleTime" value="${minEvictableIdleTimeMillis}"/>
		<property name="maintenanceInterval" value="${timeBetweenEvictionRunsMillis}"/>
		<property name="maxLifetime" value="${maxLifetime}"/>
	</bean>`

Using properties:
com.atomikos.icatch.service=com.atomikos.icatch.standalone.UserTransactionServiceFactory
com.atomikos.icatch.tm_unique_name=gtm
com.atomikos.icatch.max_timeout=1500000
com.atomikos.icatch.max_actives=-1

I'm using Tomcat 9.0.41. I've noticed the same behaviour even in TransactionEssentials 5.0.8

**Comment by GuyPardon** [comment]
We changed this timeout to a ThreadLocal for specs compliance. So it will only work via your code.
