### ISSUE TITLE
Vault Integration

### ISSUE THREAD

**Issue by arasheed** [atomikos/transactions-essentials#142]
We are using HashiCorp Vault to save DB credentials as secrets. I was wondering if anyone has done integration of Atomikos with Vault?

I won't be able to specify username and password (see below) explicitly like how I am doing currently. 

    <bean id="dataSource" class="com.atomikos.jdbc.AtomikosDataSourceBean"
          init-method="init" destroy-method="close">
        <property name="testQuery" value="SELECT 1" />
        <property name="poolSize" value="2" />
        <property name="uniqueResourceName" value="dataSource" />
        <property name="xaDataSourceClassName" value="com.mysql.cj.jdbc.MysqlXADataSource" />
        <property name="xaProperties">
            <props>
                **<prop key="user">${dbUsername}</prop>
                <prop key="password">${dbPassword}</prop>**
                <prop key="url">${dbUrl}</prop>
                <prop key="pinGlobalTxToPhysicalConnection">true</prop>
                <prop key="autoReconnect">true</prop>
            </props>
        </property>
    </bean>

**Comment by GuyPardon** [comment]
We don't have this, but Spring Boot can do this for you.

Check out this article for details: 

https://www.baeldung.com/spring-cloud-vault
