### ISSUE TITLE
Log already in use error while deploying docker container

### ISSUE THREAD

**Issue by csacharya** [atomikos/transactions-essentials#143]
ERROR: the specified log seems to be in use already. Make sure that no other instance is running, or kill any pending process if needed.
java.lang.RuntimeException: Log already in use?

**Comment by MACT280** [comment]
I have same error

**Comment by GuyPardon** [comment]
The only case where this happens is if two JVMs are trying to use the same transaction log file.

Check these properties and make sure they are unique for each JVM:

https://www.atomikos.com/Documentation/JtaProperties#Transaction_logs
