### ISSUE TITLE
I can't use mysql and oracle in one project at the same time and use transaction control

### ISSUE THREAD

**Issue by PankTan** [atomikos/transactions-essentials#144]
**Describe the bug**
I can't use mysql and oracle in one project at the same time and use transaction control

**To Reproduce**

I mainly want to know when Atomikos connects to oracle and mysql at the same time in the project, and when the code appear exception, can oracle and mysql roll back at the same time? Can Atomikos control the transactions between different databases?
I am java coder

**Comment by GuyPardon** [comment]
Yes, we can do that.
