### ISSUE TITLE
Atomikos used in the production environment is used to process distributed things after dividing databases and data. It has not been a problem before. Recently, there have been a lot of timeouts

### ISSUE THREAD

**Issue by liangxianjin** [atomikos/transactions-essentials#147]
Hello, guy pardon, I have a question to ask

My configuration

![image](https://user-images.githubusercontent.com/45254883/132478291-21dcd990-1be5-4f99-a211-f401e6323aae.png)
Warn prompt location

![image](https://user-images.githubusercontent.com/45254883/132478708-04cf2653-4a19-4e18-b8db-1a1ee92c4c27.png)

Production environment log
![image](https://user-images.githubusercontent.com/45254883/132478850-4beed013-dda0-43b1-9b3c-91e219cd2d9b.png)

Because it is timeout, I still report this prompt after enlarging the time. Please see what I need to do here

**Comment by GuyPardon** [comment]
It looks like you are not picking up the right setting. Maybe you have a second file called "jta.properties" somewhere in the classpath? If so, the values in "jta.properties" take priority.
