### ISSUE TITLE
AtomikosNonXADataSourceBean doesn't notify on closed connections

### ISSUE THREAD

**Issue by jclx** [atomikos/transactions-essentials#148]
AtomikosNonXADataSourceBean after closing connections still waits the full waitTime in com.atomikos.datasource.pool.ConnectionPool.waitForAtLeastOneAvailableConnection(long)

After a connection is closed, it should notify the synchronized block which would shorted the wait time.

Example program shows that about 9 threads wait the default borrowConnectionTimeout of 30 seconds.

```
        public static void main(String[] args) throws Exception
	{
		AtomikosNonXADataSourceBean bean = new AtomikosNonXADataSourceBean();
		bean.setMinPoolSize(4);
		bean.setMaxPoolSize(10);
		bean.setDriverClassName("...");
		bean.setUrl("....");
		bean.setUser("...");
		bean.setPassword("...");
		bean.setUniqueResourceName("java:/TestDS");
		bean.setLocalTransactionMode(true);
		bean.init();
		
		Thread threads[] = new Thread[20];
		for (int cc = 0; cc < threads.length; cc++)
		{
			threads[cc] = new Thread(new Runnable()
			{
				@Override
				public void run()
				{
					try
					{
						System.out.println("Getting Connection:" + new Date());
						Connection conn = bean.getConnection();
						Thread.sleep(1000);
						conn.close();
						System.out.println("Got connection and closed:" + new Date());
					}
					catch (Exception ex)
					{
						ex.printStackTrace();
					}
				}
			});

		}
		
		for (int cc = 0; cc < threads.length; cc++)
		{
			threads[cc].start();
		}
		for (int cc = 0; cc < threads.length; cc++)
		{
			threads[cc].join();
		}
		
		System.out.println("Done");
		
		System.exit(0);
	}
```
Example output:
Getting Connection:Tue Sep 14 16:55:38 PDT 2021
Getting Connection:Tue Sep 14 16:55:38 PDT 2021
Getting Connection:Tue Sep 14 16:55:38 PDT 2021
Getting Connection:Tue Sep 14 16:55:38 PDT 2021
....
Got connection and closed:Tue Sep 14 16:55:39 PDT 2021
Got connection and closed:Tue Sep 14 16:55:39 PDT 2021
Got connection and closed:Tue Sep 14 16:56:09 PDT 2021 - 30 seconds later
Got connection and closed:Tue Sep 14 16:56:09 PDT 2021 - 30 seconds later

**Comment by jclx** [comment]
In com.atomikos.jdbc.internal.JtaUnawareThreadLocalConnection.close() adding this line to the end, signals the notify on waiting threads.
`        pooledConnection.fireOnXPooledConnectionTerminated();`

This will signal those threads waiting in: com.atomikos.datasource.pool.ConnectionPool.waitForAtLeastOneAvailableConnection(long)

```
    public void close() throws SQLException {
        if (dirty && !delegate.getAutoCommit()) {
           try {
               rollback(); //case 175344: ensures clean connection state for reuse
           } catch (Throwable t) {
               LOGGER.logWarning(this + ": unexpected error trying to rollback on vendor connection - marking connection as erroneous so it will be replaced by the pool...", t);
               pooledConnection.setErroneous(); //avoid reuse at all cost
           }
        } 
        markClosed();
        /* add this line to wake those threads in wait
        pooledConnection.fireOnXPooledConnectionTerminated();
    }
```

**Comment by jclx** [comment]
Looks like this was already fixed in commercial version.
BUG: 189263 Long connection pool wait times when using AtomikosNonXADataSourceBean outside a JTA transaction 
5.0.99

**Comment by GuyPardon** [comment]
Thanks for the feedback!

Indeed, we fixed this for some of our customers. 

Guy

PS Not sure if you are interested but you can register for a free trial here: https://www.atomikos.com/Main/ExtremeTransactionsFreeTrial
