### ISSUE TITLE
atomikos 5.0.8 XA maxPoolSize tomcat DB2 database

### ISSUE THREAD

**Issue by numero90** [atomikos/transactions-essentials#149]
hello,

we are using  IBM DB2 database  , atomikos 5.0.8 ans sprint boot 4.2   on tomcat  with the following configuration : 
`<Resource
name="xxxx"
auth="Container"
type="com.atomikos.jdbc.AtomikosDataSourceBean"
factory="org.bonitasoft.tomcat.atomikos.EnhancedTomcatAtomikosBeanFactory "
uniqueResourceName="xxxx"
xaDataSourceClassName="com.ibm.db2.jcc.DB2XADataSource"
xaProperties.databaseName="test"
xaProperties.serverName="localhost"
xaProperties.currentSchema="test"
xaProperties.driverType="4"
xaProperties.portNumber="3306"
xaProperties.user="USER"
xaProperties.password="PASSWORD"
maxPoolSize="400"
minPoolSize="50"
/>`

After several minuits, we have an error  : connection pool exhausted - try increasing 'maxpoolSize'

Could you  help me  ?

Best regards

**Comment by GuyPardon** [comment]
Maybe connections are not released, or maybe there is a network blocking? Those things can cause this so maybe you can check for those?

Thanks

PS If you're interested then we can have a look too - as part of a free trial of our commercial offering. You can apply here:

https://www.atomikos.com/Main/ExtremeTransactionsFreeTrial
