### ISSUE TITLE
open cursor issues with JDBCTemplate + Atomikos Non XA Datasource, any clues!

### ISSUE THREAD

**Issue by Laxmikant187** [atomikos/transactions-essentials#15]
As per Spring, as it uses Template Callback pattern, developer should not be concerned about closing the resources and it works fine as well in the industry. But recently when we have tried Spring with Atomikos Non XA Datasource, we are getting Maximum open cursor issue.
is this known issue for Atomikos non XA datasource with Spring integration?

**Comment by GuyPardon** [comment]
Hi,

No, this is not a known issue. Do you have a test case we can reuse to reproduce this?

Thanks!

**Comment by GuyPardon** [comment]
Closing this issue as we got no reply - please answer to re-open?
