### ISSUE TITLE
Polling feature for connection pool

### ISSUE THREAD

**Issue by AleksDraz** [atomikos/transactions-essentials#151]
Hello.

**Feature description:**
We have next case: between application and DB is proxy firewall, which close connections by timeout.
We would like to have the atomikos datasource pool to validate connections, not only when performing the SQL request like now, but periodically, to evict erroneous connections if necessary.

**Possible solution**
Possible solution is add some daemon to ping all connections in pool like in tomcat pool(see validation-query param).

**Comment by GuyPardon** [comment]
Hi,

We actually have something like this in our commercial edition, but not in our open source.

If you're interested then you can apply for a free trial of the commercial product here:

https://www.atomikos.com/Main/ExtremeTransactionsFreeTrial

There are no current plans to include this as open source.
