### ISSUE TITLE
Is there any way to auto  close leaking connections?

### ISSUE THREAD

**Issue by bjdaijun** [atomikos/transactions-essentials#152]
**Describe the bug**
An old project with atomikos 3.9.3, and it's connections always leaking for about half day.
But I can't figure out Where is the leaking point.  And the leaking connections sometimes just  do read operations.

So I  want find a way to auto close the leaking connections, but noting workable found.
I tried  reapTimeout/maxLifetime ,no one can solve the problems.

**To Reproduce**

**Additional context**

**Comment by GuyPardon** [comment]
More recent releases collect a stack trace of the connection acquisition, so you can see (on reap) where the connections were gotten from. That allows you to fix the bug in the application code.

For 3.9.3 we did not have that yet. Maybe you can try with a newer release?
