### ISSUE TITLE
Rolled-back in-doubt transactions on multi node Apache Artemis cluster

### ISSUE THREAD

**Issue by Maverick19841972** [atomikos/transactions-essentials#153]
Hi,
We are using Atomikos for XA transactions in the following setup:
•	In-memory ActiveMQ JMS broker.
•	Postgres 11 database on localhost.
•	Apache Artemis JMS broker Cluster with two nodes on localhost.
•	Apache Camel is used for the routing.

A JMS message is picked-up from the in-memory broker and processed. As a result of this processing a new message is send to the Artemis broker. Another message is persisted to the database and also send to the Artemis broker. So a single message on the in-memory broker leads to 2 messages on the Artemis broker and one of these (the second one) is also stored in the database.

This works just fine in normal operations but if we stop and start (kill/restart) the Artemis brokers during processing in-doubt transactions occur on the Artemis broker side containing the two send messages. This is OK and expeted. However the "second" message is actually commited to the database and after a while (depending on transaction time-out settings) the in-doubt transactions are rolled-back by the client (Atomikos). The end result is that the 'first" message is lost and the "second" message is only stored in the database.
The commit to the database is probably caused by the fact that the Artemis-broker is stopped in the middle of the two-phase commit. The test is done in a high-load scenario.
We connect to the Artemis-broker using a single connection-factory using a HA (high available) connection-url.

When we scale the Artemis Cluster back to a single node everything seems to be working fine.

We checked the Atomikos logs in a single message, single consumer situation and it seems like every is included in the same XA transaction.

When we increase the transaction-timeout for Atomikos, the transaction are not rolled-back and we can manually commit/rollback them on Artemis to get everything in order again.

Any ideas on this ?

**Comment by GuyPardon** [comment]
Hi,

This is strange. If the DB is committed then the outcome of the transaction was already logged as "committing" and there should be no rollback on the broker parts.

It may be a bug in our open source edition. We have many fixes we did for our customers and that are not systematically ported to the open source code base. To determine if that is the case, you can apply for a free trial and run your test with the full distribution here:

https://www.atomikos.com/Main/ExtremeTransactionsFreeTrial

Thanks
