### ISSUE TITLE
Propagation.REQUIRES_NEW leads to com.atomikos.icatch.RollbackException: Orphans detected

### ISSUE THREAD

**Issue by aubelix** [atomikos/transactions-essentials#161]
based on transactions-over-rest-with-hybrid-jaxrs-stack we added in com.atomikos.jaxrshibernate.service.AccountServiceImpl.createAccount(Account) a call to a TestService.doTest() with @Transactional(value = TxType.REQUIRES_NEW)
This leads to a problem in ActiveStateHandler:

com.atomikos.icatch.RollbackException: Orphans detected.
	at com.atomikos.icatch.imp.ActiveStateHandler.prepare(ActiveStateHandler.java:134) ~[transactions-5.0.9.jar:na]
	at com.atomikos.icatch.imp.CoordinatorImp.prepare(CoordinatorImp.java:525) ~[transactions-5.0.9.jar:na]
	at com.atomikos.remoting.twopc.AtomikosRestPort.prepare(AtomikosRestPort.java:136) ~[transactions-remoting-5.0.9.jar:na]

localSiblingsStarted is 2 in CoordinatorImp because of the REQUIRES_NEW
But globalSiblingCount_ ist 1 in ActiveStateHandler.

We will add a forked repo of transactions-over-rest-with-hybrid-jaxrs-stack with a testcase

Full sample is available in https://github.com/aubelix/transactions-over-rest-with-hybrid-jaxrs-stack

Tested with TransactionEssentials 5.0.9 and 5.0.8

**Comment by GuyPardon** [comment]
Thanks!

I found out why based on your example:

-suspend "terminates" the sibling for rollback / timeout reasons
-resume then "increments" the sibling count
-this causes the prepare issue

The obvious solution would be not to do that. However, I need to check the implications.

**Comment by aubelix** [comment]
The reason for the REQUIRES_NEW is a unique key service that increments the last value similar to a sequence. To avoid deadlocks the key service has to commit directly after the update of the key value.

**Comment by aubelix** [comment]
unfortunately we see no workaoround as we have a large application that makes use of REQUIRES_NEW in hundreds of places

**Comment by aubelix** [comment]
Any news on this? we tried this fix in ActiveStateHandler
    private boolean orphansExist() {
    	return false;
       // return globalSiblingCount_ != getCoordinator ().getLocalSiblingCount();
    }

It works, but the implications are unclear.

**Comment by GuyPardon** [comment]
We fixed this for 5.0.10 of TransactionsEssentials

**Comment by aubelix** [comment]
where did you do a checkin? i cannot see it in https://github.com/atomikos/transactions-essentials/commits/master ?

**Comment by GuyPardon** [comment]
This is also fixed in 6.0.0M1, now online.
