### ISSUE TITLE
testQuery executed multiple times during a transaction

### ISSUE THREAD

**Issue by samion** [atomikos/transactions-essentials#18]
We are using Hibernate in our application and therefore each transaction may execute lots of SQL queries. It seems that Atomikos asks for a connection from pool for each of the queries separately and does not use the same connection for two subsequent queries. This, together with the testQuery-setting causes multiple testQueries to be executed during one transaction.

Is it possible to make use of the same connection for each SQL query during one transaction?

What happens if I disable testQuery and the connection in pool will break and is then given to application? I suppose that the operation in application will then fail and the connection will be removed from pool.

**Comment by GuyPardon** [comment]
Thanks for getting in touch!

I am not sure I understand your point re "Atomikos asks for a connection from pool for each of the queries separately ". If Hibernate "closes" the connections after each statement then I assume they would be reused?

Thanks

**Comment by samion** [comment]
Thanks for reply.

I found out that Hibernate defaults on JTA environment to close connections after each statement. It can be configured to close after transaction (hibernate.connection.release_mode). That is basically the answer to my first question.

Second part of the question was mainly about the situation when I don't use testQuery and only configure max-lifetime for database connection. I wanted to know if a broken connection would remain in the pool, even if it throws some exceptions inside application, until the max-lifetime will be attchieved.

**Comment by GuyPardon** [comment]
Hi,

We're working on making the testQuery much more performant so there should be no real need to disable it.

Without testQuery, connections that have SQL errors on them are removed from the pool - but this may not coincide with the time of breaking (but rather later, when you try to use the connection). This will give some app-level errors at that time.

Does that clarify?
Thanks

**Comment by samion** [comment]
The changes introduced in 4.0.6 version improved the performance and test query is no longer a performance problem. Thanks!

**Comment by GuyPardon** [comment]
Our pleasure :-)
