### ISSUE TITLE
Add support for connection-INIT-SQL property

### ISSUE THREAD

**Issue by AlGolUA** [atomikos/transactions-essentials#190]
This is a widely used requirement to use credentials other than the schema owner's credentials to connect to the database or call something right after connection. connection-INIT-SQL property, that can look like,
connection-INIT-SQL = BEGIN EXECUTE IMMEDIATE 'ALTER SESSION SET CURRENT_SCHEMA = MAIN'; END;
allows you to achieve this goal for Hikary pool. But it looks like the Atomikos library doesn't support anything like that.
For now we have to extend AtomikosDataSourceBean and its getConnection method by making required initialization and keeping hashCode of initialized connection in internal map (to avoid double initialization and to clear the map from old items).

**Comment by AlGolUA** [comment]
Looking for solution I have found just one question by the same topic on stackoverflow: [Atomikos equivalent to Hikari connection-init-sql](https://stackoverflow.com/questions/76556281/atomikos-equivalent-to-hikari-connection-init-sql). In any case it should be a nice extention, but lets wait for voting.

**Comment by GuyPardon** [comment]
Ah, if that's what you mean then I can tell you we have such a feature in our commercial distribution. There's a free trial if you are interested.
