### ISSUE TITLE
Support for Feign and FeignClients 

### ISSUE THREAD

**Issue by joshuapullin** [atomikos/transactions-essentials#191]
Has anyone got this working with Feign and FeignClients?

I am using Spring Boot and the current Spring support in transactions-remoting doesn't seem to support Feign (through Spring).

I have tried adding the interceptors via config and exceptions get thrown due to the different class types required. I was just wondering if this is something someone has a working solution for or if there is any support for this coming in the future?

Spring Cloud OpenFeign is heavily used through the APIs so would prefer to keep this functionality in place to reduce the amount of rework required.

**Comment by GuyPardon** [comment]
Sorry, only noticed this just now. Care to comment on why it is completed?

**Comment by joshuapullin** [comment]
Adding a custom RequestInterceptor and ResponseInterceptor was needed for the Feign clients.

**Comment by GuyPardon** [comment]
Got it. Did you consider contributing the code for those?

**Comment by joshuapullin** [comment]
I haven't finalised the development yet as it is for the company I work for. 
If I get time once complete, I might try to.

**Comment by GuyPardon** [comment]
OK thanks let me know...

**Comment by Moline-x** [comment]
I think I have this issue too, can help add feign client support?

**Comment by Moline-x** [comment]
> Adding a custom RequestInterceptor and ResponseInterceptor was needed for the Feign clients.

Hi @joshuapullin  , may I know how you implement code for this , because I also met issues when executing atomikos and feign client
