### ISSUE TITLE
Some times throws 'com.atomikos.datasource.xa.XATransactionalResource:24 - Error in recovery'

### ISSUE THREAD

**Issue by borodatu** [atomikos/transactions-essentials#20]
The full log is in attached log file.
[ERROR IN RECOVERY.log](https://github.com/atomikos/transactions-essentials/files/1563910/ERROR.IN.RECOVERY.log)
Configuration attached below
[spring-mybatis-config_xml.txt](https://github.com/atomikos/transactions-essentials/files/1563923/spring-mybatis-config_xml.txt)
What the reason of this?
Thank you!

**Comment by GuyPardon** [comment]
This looks like a support issue - do you have a budget for a paid subscription?

Thanks

**Comment by borodatu** [comment]
How much?

**Comment by GuyPardon** [comment]
Assuming you can upgrade to 4.0.5: "basic" would do (see https://www.atomikos.com/Main/BuyOnline)

We also have a free trial (no cure, no pay) but then you would need to go for "professional" if it works.

**Comment by borodatu** [comment]
Thanks @GuyPardon, but I'm afraid such price is too expensive. It could be great if could tell the possible reason of that, what those exceptions means, to understand the direction of investigation.

**Comment by GuyPardon** [comment]
Well it is not a known issue so I can't say much from what I see. Perhaps you can log in DEBUG mode and find a hint about the cause. If you had a budget then we could help you do that, but feel free to experiment...
