### ISSUE TITLE
Atomikos for HP Vertica

### ISSUE THREAD

**Issue by ganesanradhika** [atomikos/transactions-essentials#22]
Hello,

Has anyone set up Atomikos for HP Vertica DB. When i look at Vertica version 7 (/8/9) , I do not see any class that implements javax.sql.XADataSource.

I am not sure how to set it up with Spring, Hibernate, Atomikos.

Please help !

Thanks and Regards,
Radhika Ganesan

**Comment by GuyPardon** [comment]
Not sure, but from the website it looks like Vertica is an analytics DB, not an OLTP DB. This means they probably do not support XA.

Does anybody have better information?
