### ISSUE TITLE
Explicit Last Resource Commit Optimization support

### ISSUE THREAD

**Issue by vlotarev** [atomikos/transactions-essentials#33]
Dear team,

I am wondering whether Atomikos has explicit support for LRCO? We are experiencing rather serious problems with consistency using Atomikos with non-XA resource ... I just want to understand whether try to solve an issue with Atomikos or just to switch to another transaction manager (say Narayana).

Thanks,
Vadim

**Comment by GuyPardon** [comment]
We have something similar like LRCO, but I would recommend against using either. It's just not safe - so it's quite normal that you are facing consistency issues. The same thing would happen with Narayana if you use LRCO.

**Comment by vlotarev** [comment]
Re: [atomikos/transactions-essentials] Explicit Last Resource Commit Optimization support (#33)


Is that "similar" used implicitly or should be configured somehow?

**Comment by GuyPardon** [comment]
The AtomikosNonXADataSourceBean works similarly.

**Comment by vlotarev** [comment]
Re: [atomikos/transactions-essentials] Explicit Last Resource Commit Optimization support (#33)


Guy,

Do you have any examples of this bean usage?

Thanks,
Vadim

**Comment by vlotarev** [comment]
Re: [atomikos/transactions-essentials] Explicit Last Resource Commit Optimization support (#33)


Well, I understand how AtomikosNonXADataSourceBean can be used with the database but I can not understand how to use it with other sources (not jdbc). Is it possible?

**Comment by GuyPardon** [comment]
Hi,

No, other than JDBC we don't support this.

Guy
