### ISSUE TITLE
XA resource has become unavailable XID raised -7

### ISSUE THREAD

**Issue by MysariRaghav** [atomikos/transactions-essentials#38]
I am getting below error in a random way. It doesn't throw error initially but after a while the error is thrown. Once I restart my server everything gets reset and error is not thrown.

XA resource 'XXXXAtomikosDataSource': resume for XID '31302E3137382E36382E3235302E746D30303031353030303138:31302E3137382E36382E3235302E746D3135' raised -7: the XA resource has become unavailable

I am using below dependencies.

   <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-jta-atomikos</artifactId>
        <version>1.4.2.RELEASE</version>
   </dependency>
And with configuration beans

    @Bean(name= "userTransaction")
    public UserTransaction userTransaction() throws Throwable {
       UserTransactionImp userTransactionImp = new UserTransactionImp();
       userTransactionImp.setTransactionTimeout(10000);
       return userTransactionImp;
    }

    @Bean
    @Primary
    public TransactionManager atomTransactionManager() throws Throwable {
        UserTransactionManager userTransactionManager = new UserTransactionManager();
        userTransactionManager.setForceShutdown(false);

        return userTransactionManager;
    }

    @Bean("atomikosTransactionManager")
    public PlatformTransactionManager platformTransactionManager()  throws Throwable {
        UserTransaction userTransaction = userTransaction();
        TransactionManager transactionManager = atomTransactionManager();

        JtaTransactionManager jtaTransactionManager = new JtaTransactionManager(userTransaction, transactionManager);
        jtaTransactionManager.setAllowCustomIsolationLevels(true);

        return jtaTransactionManager;
    }

    @Bean(name = "atomikosDataSources")
    public Map<String, DataSource> atomikosDataSources(PropertiesFactoryBean databaseProperties, Environment environment, BcusDefaultEncrytor bcusDefaultEncrytor) throws SQLException, IOException {

        List<String> databases= Collections.list(databaseProperties.getObject().propertyNames()).stream().map(key->key.toString()).filter(key-> key.contains("url")).collect(Collectors.toList());

        Map<String, DataSource> collect = databases.stream().collect(Collectors.toMap(dbName -> dbName.split("\\.")[0].toUpperCase() + "AtomikosDataSource", dbName -> {

            OracleXADataSource dataSource = null;
            try {
                dataSource = new OracleXADataSource();
                dataSource.setURL(environment.getProperty(dbName));
                dataSource.setUser(environment.getProperty("database.username"));
                dataSource.setPassword(bcusDefaultEncrytor.decryptQAPassword(environment.getProperty("database.password")));
            }
            catch (SQLException e)
            {
                LOG.error(
                        "DatabaseConditionException [errorCode= Error while configuring atomikos data sources- Could not OracleXADataSource object, errorMessage= {} ]",
                        e.getMessage());
            }
            catch (Exception e) {
                LOG.error(
                        "DatabaseConditionException [errorCode= Error while configuring atomikos data sources- Could not decrypt QA Password make sure you have proper **QA** Encryption password in your folder, errorMessage= {} ]",
                        e.getMessage());            
            }

            AtomikosDataSourceBean xaDataSource = new AtomikosDataSourceBean();
            xaDataSource.setXaDataSource(dataSource);
            xaDataSource.setUniqueResourceName(dbName.split("\\.")[0].toUpperCase() + "AtomikosDataSource");
            xaDataSource.setPoolSize(5);
            return xaDataSource;
        }));
        return collect;
}

**Comment by GuyPardon** [comment]
Not a known issue AFAIK. We offer a free trial with free support, would you be interested in that?

**Comment by abuinteam** [comment]
I can still seeing the same issue with atomikos 4.0.6 version with spring boot 2.0.1.RELEASE. Will there be any fix for this?

**Comment by GuyPardon** [comment]
Closing - without more context it is impossible to say anything.
