### ISSUE TITLE
Tomcat Atomikos Issue

### ISSUE THREAD

**Issue by AtomikosIssue** [atomikos/transactions-essentials#42]
I am using Tomcat 8.0.4. Application using Atomikos jars for transaction handling and db2 data source.

com.atomikos.icatch.service=com.atomikos.icatch.standalone.UserTransactionServiceFactory
com.atomikos.icatch.log_base_dir=/apps/logs/tomcat
com.atomikos.icatch.output_dir=${com.atomikos.icatch.log_base_dir}
com.atomikos.icatch.console_log_level=INFO
com.atomikos.icatch.max_actives=-1
spring.jta.atomikos.properties.threaded-two-phase-commit=true
com.atomikos.icatch.threaded_2pc=true
com.atomikos.icatch.default_jta_timeout=3300000
com.atomikos.icatch.max_timeout=3300000

what are the compatible versions of jars for db2 ( 1.0 / 1.4.2) and atomikos jars (3.7.1 / 4.0.4/ 4.0.6)  for better transactiona handling. is there any option to autocommit the db2 transactions.

Mar 22, 2018 11:37:59 AM com.atomikos.logging.JULLogger logWarning
WARNING: XA resource 'vip_app': resume for XID '31302E3131332E3134362E3235332E746D313532313733363637393738393030303139:31302E3131332E3134362E3235332E746D3138' raised -9: the XA resource is currently involved in a local (non-XA) transaction
com.ibm.db2.jcc.am.vo: [jcc][t4][10401][12066][3.57.110] XA exception: XAER_OUTSIDE ERRORCODE=-4228, SQLSTATE=null
	at com.ibm.db2.jcc.am.bd.c(bd.java:453)

getting these errors more often with each db transaction

**Comment by vijayakumar-balraj** [comment]
we also face the same problem in our application, is there any fix available to resolve above mentioned issue?

**Comment by GuyPardon** [comment]
Closing issue since there is no feedback. If you want help, please consider a free trial of ExtremeTransactions where I am sure we can fix this for you.
