### ISSUE TITLE
Connection pool is exhausted when application throws an exception 

### ISSUE THREAD

**Issue by pavan2017** [atomikos/transactions-essentials#43]
in my standlone  application am using atomikos to controlling transaction.Problem is whenever my application is throwing exception, connection is getting exhausted and is not getting acquired.Am using atomikos 3.9.3 .Can someone help me in fixing this.I configured it following http://fabiomaffioletti.me/blog/2014/04/15/distributed-transactions-multiple-databases-spring-boot-spring-data-jpa-atomikos/

**Comment by pavan2017** [comment]
it works when i configure atomikos with spring .

**Comment by GuyPardon** [comment]
OK thanks, looks like transaction were not terminated - thereby keeping the connections from being reused?

**Comment by pavan2017** [comment]
I am able to reproduce it using transaction template .When application throws many exceptions atomikos connection pool is breaking

**Comment by GuyPardon** [comment]
Closing since this looks like an application / configuration issue.

**Comment by rmaheedharan** [comment]
@GuyPardon @pavan2017 can you help me with what was done to resolve this situation? I am running into similar situation where the connection pool is getting exhausted whenever there is a transaction timeout.

**Comment by GuyPardon** [comment]
Nothing was done yet.
