### ISSUE TITLE
TMJOIN issue

### ISSUE THREAD

**Issue by harpreetsa87** [atomikos/transactions-essentials#45]
Hey 

We are trying to use Atomikos to perform XA transaction with DB2 and IMS ( IBM SQL Based DB )
The IMS DB is throwing error when a call is made with TMJOIN

`XAResource.start ( 31392E33392E35332E3233352E746D30303030333030303733:31392E33392E35332E3233352E746D35 , XAResource.TMJOIN )
`
> javax.transaction.xa.XAException: Transactional protocol violation. Current transactional state: "TRAN_XA_ENDED" Transactional command issued: XA Start

We tried setting the property **com.atomikos.icatch.serial_jta_transactions** to **false** still TMJOIN call is being triggered.

It seems like the IMS DB does not support the TMJOIN, as this worked just fine with DB2, MYSQL, H2.
We are trying to get help from the IBM for that.

However we wanted to check with the Atomikos team if we have a workaround to disable the TMJOIN calls in case our DB does not support this.

**Comment by GuyPardon** [comment]
TMJOIN can be disabled as part of the performance features pack in our "professional" subscription.
