### ISSUE TITLE
Replace no longer supported Atlassian clover product with the free OSS openclover version

### ISSUE THREAD

**Issue by andyglick** [atomikos/transactions-essentials#48]
Gentlemen,

Your parent pom is referencing the old and no longer supported Atlassian commercial version of the clover code coverage plugin and library

         <plugin>
           <groupId>com.atlassian.maven.plugins</groupId>
           <artifactId>maven-clover2-plugin</artifactId>
           <version>3.0.1</version>
         </plugin>

Were I you I would replace it with the new kid on the block, the free and OSS release from openclover

        <plugin>
          <groupId>org.openclover</groupId>
          <artifactId>clover-maven-plugin</artifactId>
          <version>4.2.1</version>
        </plugin>

Hope that this helps, :-)

Andy

**Comment by GuyPardon** [comment]
Thanks! Not sure if we use clover, this may be an orphaned dependency. If it's now open source then maybe we can start using it, thanks for the tip!

**Comment by GuyPardon** [comment]
Removed for the 4.0.7 and 5.0
