### ISSUE TITLE
JTA Transaction timeout always use default

### ISSUE THREAD

**Issue by tranquoctu1988** [atomikos/transactions-essentials#51]
I have a strange behavior when upgrade from v4.0.M4 to 4.0.6. That the transaction timeout will not respect value setting in J2eeUserTransaction. I have this configuration
> @Bean
> @DependsOn("userTransactionService")
> public UserTransaction atomikosUserTransaction() throws SystemException {
>        final J2eeUserTransaction result = new J2eeUserTransaction();
>         result.setTransactionTimeout(300);
>         return result;
>}

At version 4.0.M4, JTA transaction will start with 300s timeout, but not 300s at V4.0.6 when I debug in com.atomikos.icatch.jta.TransactionManagerImp.begin ( int timeout ), timeout value alwas 10.

To work around, I have to set timeout value of JtaTransactionManager too
> @Bean()
>    public PlatformTransactionManager transactionManager() throws SystemException {
>        final JtaTransactionManager jtaTransactionManager = new JtaTransactionManager();
>        jtaTransactionManager.setTransactionManager(atomikosTransactionManager());
>        jtaTransactionManager.setUserTransaction(atomikosUserTransaction());
>        // In version 4.0.6, setting timeout in JtaTransactionManager will override default timeout in TransactionManagerImp (10s is default).
>        jtaTransactionManager.setDefaultTimeout(env.getProperty("transaction.transactionTimeout", Integer.class));
>        return jtaTransactionManager;
>    }
>
>
So, it is a bug or in V4.0.6 some new configuration way are applied?

**Comment by GuyPardon** [comment]
Not sure what you mean, but com.atomikos.icatch.default_jta_timeout=10000 (millis) is the default unless you override it in your jta.properties or as a system property.

Why does that seem odd? Or did I misunderstand?
