### ISSUE TITLE
contention at sys.dbms_xa.dist_txn_sync after upgrading from 3.9.3 to 4.0.6

### ISSUE THREAD

**Issue by ftamios** [atomikos/transactions-essentials#52]
After upgrading atomikos from 3.9.3 to 4.0.6 in production it's been observed contention at sys.dbms_xa.dist_txn_sync. The number of calls increased a lot, it's 10 times more now. 
sys.dbms_xa.dist_txn_sync procedure is always called on xa_recover, xa_commit and xa_rollback according to http://www.oracle.com/technetwork/products/clustering/overview/distributed-transactions-and-xa-163941.pdf.  Oracle Doc ID 2332314.1 says it's not a bug, but it's related how application or frameworks use it.
As the number of transactions didn't change, why do we see this behavior? Is it due to new recovery process mentioned at https://fogbugz.atomikos.com/default1a5f.html?community.6.3514.11? 
Is there any recommendation or any fix planned in order to optimize that?

**Comment by GuyPardon** [comment]
Hi,

Thanks for the feedback!

This could indeed be related to the new recovery. Do you have many datasources that actually connect to the same DBMS server?

**Comment by ftamios** [comment]
Yes. There is only one database instance with multiple nodes. There are about 11 datasources.

Fabiana Tamiosso | Software Architect,
ADPLabs Porto Alegre

+55 51 3327-1411 office
+55 51 8175-6070 mobile
fabiana.tamiosso@adp.com<mailto:fabiana.tamiosso@adp.com>

Av. Soledade 550, Porto Alegre - RS
[email-logo]<http://www.adp.com/>[LinkedIn]<https://www.linkedin.com/company/adp>[Twitter]<https://twitter.com/ADP>[Facebook]<https://www.facebook.com/AutomaticDataProcessing>[Youtube]<https://www.youtube.com/user/adp>[cid:image010.jpg@01D12DED.821183A0]<http://bit.ly/1m04LZP>

**Comment by GuyPardon** [comment]
The new recovery indeed does a bit more work if you have the same backed registered in different datasources or connection factories. Is this is serious problem? A workaround would be to (re)use the same datasource with a higher pool size.

Let me know what you think?

**Comment by ftamios** [comment]
For our application it is critical. As there are multiple services and multiple schemas, it's not a simple change to use one single datasource. In parallel, we started migrating the current database to multiple instances. I's expecting to solve this problem, but I believe there are others related. The sys.dbms_xa.dist_txn_sync has been called in all instances even if they are not involved in the transactions.

**Comment by GuyPardon** [comment]
OK. We planned this for our 5.0, but if you're interested in a paid subscription then we can fix this sooner on the 4.0 codebase.

Let me know if that is of interest to you?

**Comment by ftamios** [comment]
Is there a timeline to 5.0? Should the fix also remove sys.dbms_xa.dist_txn_sync calls to instances that don't have transaction branches?

**Comment by GuyPardon** [comment]
The timeline is Q1/Q2 2019 for now but it's not a hard one since this will be a significant new release.

What do you mean with "remove sys.dbms_xa.dist_txn_sync calls to instances that don't have transaction branches"?

Thanks

**Comment by ftamios** [comment]
Considering there are 2 DB instances A and B, but B contains no data. One transaction occurs only in DB A using multiple datasources. Although nothing runs in DB B, we see sys.dbms_xa.dist_txn_sync calls there. Why? Is it coming from the recover process?

**Comment by GuyPardon** [comment]
Yes, recovery works on all registered datasources.
