### ISSUE TITLE
AtomikosThreadLocalConnection memory issues

### ISSUE THREAD

**Issue by nniesen** [atomikos/transactions-essentials#53]
The AtomikosThreadLocalConnection is causing OutOfMemoryExceptions in large JPA transactions. The statements are added to the statements list on AbstractConnectionProxy and even if completed/closed (by flush or commit) they cannot be garbage collected until the reaper calls forceCloseAllPendingStatements which may not happen depending on the min/max pool size settings.

Noted Issues:
1. Statements are not released when the connection is returned to the pool (only when reaped or terminated).
1. Statements are not released when closed/flushed. Large transactions need to be flushed to the database to free up resources.
1. The forceCloseAllPendingStatements logs that it's force closing potentially thousands of already closed connections. 

This [mssql.zip](https://github.com/atomikos/transactions-essentials/files/2102999/mssql.zip) gradle project can be used to demonstrate the issue and potential resolutions. See the projects readme.md.

![mssql-atomikos-4 0 6-c300k-fc50k](https://user-images.githubusercontent.com/4194475/41419675-3558fa38-6fb8-11e8-8ff3-fa2dc2587c7e.png)
![mssql-atomikos-newcommit-c300k-fc50k](https://user-images.githubusercontent.com/4194475/41419676-3564ad56-6fb8-11e8-9ac0-740f95a85e25.png)
![mssql-atomikos-newflushandcommit-c300k-fc50k](https://user-images.githubusercontent.com/4194475/41419673-35493cb0-6fb8-11e8-88d5-56bddc8e5bef.png)

**Comment by nniesen** [comment]
Pull request: https://github.com/atomikos/transactions-essentials/pull/57

**Comment by nniesen** [comment]
Memory profile of a large transaction that previously needed ~16GB heap:
![image](https://user-images.githubusercontent.com/4194475/43985154-c58dd8d2-9cca-11e8-9d23-fa3e8b0bfd96.png)

**Comment by nniesen** [comment]
Memory profile of a large transaction that previously needed ~16GB heap:
![image](https://user-images.githubusercontent.com/4194475/43985271-ac11cad4-9ccb-11e8-8ec5-e42677ff2d5e.png)

**Comment by GuyPardon** [comment]
Sorry for the late reply, and thanks for the elaborate documentation!

Let me have a look if this can go into 4.0.7

**Comment by GuyPardon** [comment]
Update: added this for the 5.0 - which has better proxies for JDBC and thus also better close behaviour.

**Comment by GuyPardon** [comment]
@nniesen Closing this issue: it was fixed for the 5.0 release - soon to be published.

**Comment by reynderbierens** [comment]
@GuyPardon : This issue implies huge gains for one of our projects. We've tried to implement TransactionsEssentials 5.0, but the impact is too big. When will TransactionEssentials 4.0.7 be released?

**Comment by GuyPardon** [comment]
Actually, we dropped plans for 4.0.7 in favour of 5.0...
