### ISSUE TITLE
how to configure JMX support for Aotmikos in version 4.0.4

### ISSUE THREAD

**Issue by gxf1027** [atomikos/transactions-essentials#55]
Hi,
I am facing a problem when configure jmx for Atomikos in 4.0.4.
This article （[https://www.atomikos.com/Documentation/TomcatSpringActiveMQMySQLJMXIntegration](url)） shows the configuration includes JMX support for Atomikos. 
BUT, I can't find class (**JmxTransactionService**）, or even package "com.atomikos.icatch.admin.jmx", from version 4.0.4 (**transactions-4.0.4.jar**). 
So, could you explain how to configure JMX support for Aotmikos, since version 4.0.4 (maybe 4.0+)?
Thanks a lot.

**Comment by GuyPardon** [comment]
Hi,

The JMX has been removed from the 4.0 public sources - you can recompile the 3.9.3 JMX separately if you want.

**Comment by gxf1027** [comment]
Thank you for immediate reply.

**Comment by jecuendet** [comment]
So if I use the paid version 4.0.80 of Atomikos, how do I coènfigure JMX?
Thanks,

**Comment by apolloj** [comment]
Hi, 

Has someone managed to configure JMX support for Atomikos (v5) with Spring pls ?

Thanks in advance
