### ISSUE TITLE
Error in timeout of INDOUBT state: Transition not allowed: IN_DOUBT to ABANDONED

### ISSUE THREAD

**Issue by jenopob** [atomikos/transactions-essentials#58]
> a web app deployed one many servers , when run for a period of time , any server may happen the warn logs as follows,I want to konw the reason , and how to solve them. thanks all.

`2018-09-12 22:22:24,755 [Atomikos:755] WARN  [com.atomikos.icatch.imp.IndoubtStateHandler] - Error in timeout of INDOUBT state: Transition not allowed: IN_DOUBT to ABANDONED
2018-09-12 22:22:24,755 [Atomikos:983] WARN  [com.atomikos.icatch.imp.IndoubtStateHandler] - Error in timeout of INDOUBT state: Transition not allowed: IN_DOUBT to ABANDONED`

**Comment by jenopob** [comment]
I am using atomizes4.0.2

**Comment by GuyPardon** [comment]
Apologies for the late reply. This should be fixed in the 4.0.6 (maven central).
