### ISSUE TITLE
Spring boot 2.0 + jta-atomikos 4.0.6 + jpa + mysql combine and use AbstractRoutingDataSource to switch between dynamic data sources

### ISSUE THREAD

**Issue by lbyjwwyqt147** [atomikos/transactions-essentials#60]
Now the problem code is located at line com.atomikos.util.IntraVmObjectFactory.class 54 row

Try {
         Object existing = IntraVmObjectRegistry.getResource(name);
         If (existing != object) {
                String msg = "Another resource already exists with name " + name + " - pick a different name";
                Throw new NamingException(msg);
          }
     } catch (NameNotFoundException var5) {
          IntraVmObjectRegistry.addResource(name, object);
     }

The details of the problem are described as follows:
There are three data sources: data source A, data source B, and data source C.
In the first initialization, because IntraVmObjectRegistry.getResource(name) did not get the resource, it can run normally.
The second time you need to switch to data source A, or data source B, or data source C, the same name resource already exists when the first initialization occurs.
Object existing = IntraVmObjectRegistry.getResource(name);
If (existing != object) {
      String msg = "Another resource already exists with name " + name + " - pick a different name";
      Throw new NamingException(msg);
 }
And throwing an exception causes the program to not work properly.

Is there a solution that can make
If (existing != object) {
      String msg = "Another resource already exists with name " + name + " - pick a different name";
      Throw new NamingException(msg);
 }
When the condition is met, replace the existing resource existing with object?

**Comment by GuyPardon** [comment]
Hi, we don't have such a possibility yet. Can you elaborate a bit why or how this happens?

**Comment by GuyPardon** [comment]
Closing due to no response - please re-open if this is still current and you can give more context?
