### ISSUE TITLE
Is there a way deploying atomikos in server side.

### ISSUE THREAD

**Issue by cherrylzhao** [atomikos/transactions-essentials#73]
hi guys

I have known we can startup a atomikos  in client side to coordinate transactional resource as XA protocol defined, and XA recovery execute based on local filesystem.
Is there a way that we can deploy atomikos in server side, so transactional resource will be enlisted using http or rpc way? I have reviewed the atomikos recovery, it seems that the uri of participate can start with "http", so atomikos can support server deploy way?

**Comment by GuyPardon** [comment]
Did you see this? https://www.atomikos.com/Blog/TransactionalRESTMicroservicesWithAtomikos

It might be what you need...

**Comment by GuyPardon** [comment]
OK, you can get it here: https://www.atomikos.com/Main/ExtremeTransactionsFreeTrial

Best
