### ISSUE TITLE
transactions-hibernate3 -> ConnectionProviderTestJUnit -> testConnectionProviderXaDataSource Fails

### ISSUE THREAD

**Issue by klebeer** [atomikos/transactions-essentials#76]
In your latest code commit, (hash: 9133481388ba7623c8694cd287c56f1b6484b217)

The module **transactions-hibernate3** 

Test on **ConnectionProviderTestJUnit -> testConnectionProviderXaDataSource**  always Fails

Problem is that on  class **com.atomikos.jdbc.internal.AtomikosXAPooledConnection**

there is a new flag, and always is **true**

```java
private static boolean isJdbc4Compatible = true;
```

Because **testConnectionProviderXaDataSource** mocks XADatasource, 

this code always thows CreateConnectionException

```java
 if (!connection.isValid(queryTimeout)) {
     throw new CreateConnectionException ("Connection no longer valid");
}
```

**Comment by GuyPardon** [comment]
Thanks, our jenkins found out as well :-) I just pushed again - should be ok now?

**Comment by klebeer** [comment]
yes!
thanks!
