### ISSUE TITLE
Create NonXA Session with XAConnectionFactory

### ISSUE THREAD

**Issue by hemantgupta83** [atomikos/transactions-essentials#78]
**Describe the bug**
Atomkios doesnt return Non-XA session when JTA transaction not active. 

**To Reproduce**

 1. Create a JMS Sender from JMSXA ConnectionFactory without JTA active
2. Send message
 2. it will give exception JTA is not active

**Additional context**
Most of the JMS provider checks if transaction is not active automatically return non xa session and if transaction is active ignore all sessionTransactedFlag and ackknowledge mode which is correct from JTA spec.

In Atomkios it has facility to enable ignoreSessionTransactedFlag to false but in this case it should identify that if current JTA is active or not instead of only depending on passed flag
I have attached changed file.

[AtomikosJmsConnectionProxy.zip](https://github.com/atomikos/transactions-essentials/files/2840900/AtomikosJmsConnectionProxy.zip)

**Comment by GuyPardon** [comment]
Hi,

Thanks but I have a question: why is the current behaviour problematic? If you want to do non-JTA JMS then what stops you from using another connection factory? In other words: why not specify a JMS connection factory with localTransactionMode = true?

When designing this, we thought it would be confusing to allow regular (not locally-transacted) sessions to be created when there is no JTA transaction.

Thanks

**Comment by hemantgupta83** [comment]
Hi,
In that case you will have to have multiple connectionFactory and you need to make sure in your code in different places which conncetionFactory needs to be used if JTA is active or not.

This is also given by JMS spec. see https://javaee.github.io/tutorial/jms-concepts004.html .

**Comment by hemantgupta83** [comment]
Hi,
From my understanding is as below.

  1.  IF JTA is active ignore all sessionTransacted flag and Acknowledge mode.
  2.  IF JTA is not active and Acknowledge mode is AUTO then ignore sessonTranscted flag and messages should be committed on JMS.
  3.  IF JTA is not active and sessionTransacted Mode is true and Acknowledge Mode is other than AUTO then jms client should manage transaction and call session.commit.

Thanks & Regards,
Hemant Gupta


From: Hemant Gupta
Sent: Tuesday, February 12, 2019 6:06 AM
To: 'atomikos/transactions-essentials' <reply@reply.github.com>; atomikos/transactions-essentials <transactions-essentials@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [atomikos/transactions-essentials] Create NonXA Session with XAConnectionFactory (#78)

Hi,
In that case you will have to have multiple connectionFactory and you need to make sure in your code in different places which conncetionFactory needs to be used if JTA is active or not.

This is also given by JMS spec. see https://javaee.github.io/tutorial/jms-concepts004.html .

**Comment by hemantgupta83** [comment]
Hi 

Any update for this issue?

**Comment by GuyPardon** [comment]
Not yet - it's on the whiteboard here in our office :-)

**Comment by GuyPardon** [comment]
I asked our customers and they prefer to keep the current behaviour. A separate connection factory for non-xa sessions is recommended...
