### ISSUE TITLE
Enlisting multiple non-xa datasources within a JTA transaction succeeds with local commits to each resource

### ISSUE THREAD

**Issue by Mobe91** [atomikos/transactions-essentials#83]
I am using Atomikos with Spring and 2 Non-XA datasources. I have activated JTA transactions on my JPA configuration.
My expectation is that the Atomikos JTA transaction manager will throw an error when more than 1 Non-XA datasource is enlisted with a JTA transaction but instead, the two datasources are committed independently. Is this behavior somehow configurable? Or maybe I am misunderstanding something. Could not find anything in the docs.

**Comment by GuyPardon** [comment]
Do you mean the AtomikosNonXADataSourceBean? 

It allows commit, since people typically use it for the following:

- read-only queries on static databases as part of a JTA transaction (avoids the XA setup of the DBMS)
- JTA transactions with only one resource
-in rare cases where the backend is not XA compliant, people also use it (but at risk)

You' re right, we might be a bit more explicit with warnings on two-phase commit. What do you think?

**Comment by Mobe91** [comment]
> Do you mean the AtomikosNonXADataSourceBean?

Yes

I am using non-xa datasource because I actually want to avoid 2PC - I basically just want to have different connection pools for different parts of my application for isolation purposes and with JTA I can avoid having to deal with multiple transaction managers.

What I want to specifically avoid is that an application developer (accidentally or deliberately) uses two non-xa resources in a transaction and expects an atomic commit to happen - currently it looks like that if you do not take a closer look. I would like to be able to configure at least a warning to be logged in this situation if not a rollback of the JTA transaction in progress.

> read-only queries on static databases as part of a JTA transaction

This actually sounds useful, maybe it would be ok to allow multiple non-xa resources as long as at most one of them is writeable (again, configurable).

**Comment by Mobe91** [comment]
Here is a thread for Wildfly AS that talks about this topic: https://developer.jboss.org/thread/183198
They also have a property to allow JTA transactions with multiple non-xa resources (implying non-atomic commits) but it is disabled by default.

**Comment by GuyPardon** [comment]
OK thanks. I just committed a change to make prepare fail for non-xa. This can be overridden by setting the datasource to "readOnly" - where it is legitimate. What do you think?

**Comment by GuyPardon** [comment]
> I am using non-xa datasource because I actually want to avoid 2PC - I basically just want to have different connection pools for different parts of my application for isolation purposes and with JTA I can avoid having to deal with multiple transaction managers.

Not sure if I understand this point, but it sounds interesting. Can you clarify?

**Comment by Mobe91** [comment]
> OK thanks. I just committed a change to make prepare fail for non-xa. This can be overridden by setting the datasource to "readOnly" - where it is legitimate. What do you think?

Can I see the change somewhere? At least I don't see it on GitHub 😄 
But it sounds fine. Oh and I guess as long as the JTA transaction is read only, the type of the datasources should not matter, right?

> Not sure if I understand this point, but it sounds interesting. Can you clarify?

If I used XA datasources then a 2PC would be carried out when multiple datasources participate in the transaction - this is slow and also unnecessary in my case because all datasources actually point to the same database. My backend serves 2 different frontend applications with different categories of users. I want to be able to apply different db connection settings for these applications and also I do not want potential connection leakage in one application to affect the users of the other application.

**Comment by GuyPardon** [comment]
> Can I see the change somewhere? At least I don't see it on GitHub

I was waiting for the tests to finish. Now it's on github.

**Comment by GuyPardon** [comment]
@Mobe91 if you have time for a quick review then I'd be interested in your thoughts - thanks

**Comment by Mobe91** [comment]
I ran some tests, looks good. However, in case of a readOnly transaction with writeable datasources an exception is thrown as well - shouldn't this be allowed?

**Comment by GuyPardon** [comment]
What do you mean by a "readOnly transaction with writeable datasources"?

Thanks

**Comment by Mobe91** [comment]
In Spring, a transaction can be marked as read-only independent of the underlying datasource. E.g. Spring integrates this flag with Hibernate in `org.springframework.orm.hibernate5.SpringJtaSessionContext` to prevent auto-flushing for read-only transactions. But yeah.. this is merely a hint. Also, the flag is not even forwarded to the underlying JTA infrastructure in `org.springframework.transaction.jta.JtaTransactionManager#doJtaBegin` so I guess it is irrelevant.

**Comment by GuyPardon** [comment]
Well, it is a configuration / design decision to make the datasource "readOnly" by setting the corresponding property. Then it will not throw. Other uses are not really safe with respect to 2-phase commit so I don't see what else we can do?

**Comment by Mobe91** [comment]
Yeah that is also what I think -  so IMHO it is fine with the change you made! 👍 
Thanks for the quick fix :) when is the release scheduled that will contain your change?

**Comment by GuyPardon** [comment]
Implemented.

**Comment by Mobe91** [comment]
@GuyPardon 
> Good point. Let me have a look...

What exactly did you implement?

**Comment by GuyPardon** [comment]
Subtransactions are now supported
Multiple read-only instances can be used in the same transaction
Non-read-only instances will fail if used in two-phase commit

Will push to GitHub soon.
