### ISSUE TITLE
Hibernate 5 support

### ISSUE THREAD

**Issue by raghuveerd** [atomikos/transactions-essentials#93]
**Is your feature request related to a problem? Please describe.**
Hello, I wanted to check when would the support for Hibernate 5 be available.

**Describe the solution you'd like**

**Describe alternatives you've considered**
We are on Hibernate 4 and were able to setup Atomikos. We now want to move to Hibernate 5.

**Additional context**

**Comment by sabbynair** [comment]
We are looking at the same as well. Will it be possible to get any approximate dates/timelines for this ?

**Comment by GuyPardon** [comment]
Our 5.0 will have Hibernate5 examples. Coming soon.
