### ISSUE TITLE
No exception thrown when "The function COMMIT: failed. The status is: -4."

### ISSUE THREAD

**Issue by jcarnus** [atomikos/transactions-essentials#94]
**Describe the bug**
We use atomikos to manage 2 databases.
We have randomly having error 
"The function COMMIT: failed. The status is: -4. Error: "*** SQLJDBC_XA DTC_ERROR Context: xa_commit, state=1, StatusCode:-4 (0xFFFFFFFC) ***"

while I am not searching the root cause of this exception, the issue is that the Atomikos is not throwning any exception to Spring. This is a duplicate of bug https://github.com/atomikos/transactions-essentials/issues/70 but on the 4.0.6

What is the expected behavior we should have ?

Thanks

**Comment by GuyPardon** [comment]
Commit errors by default lead to retries. If the retry works, there will be no exception in Spring so I suspect this is fine.

**Comment by GuyPardon** [comment]
Is this for release 4.0 or 5.0?

**Comment by jcarnus** [comment]
This is for 4.0.6. Do you have some Idea ?

**Comment by GuyPardon** [comment]
It looks like a transient error that is not rethrown because we assume that recovery has done the commit. So we assume commit does not really fail - which is why we don't throw either.

Does that make sense?

**Comment by jcarnus** [comment]
Yes but the fact is recovery doesnt done the commit. This is even worse than within the transaction we can have the primary key of an added entity in DB but after, we are not able to find this row in DB

**Comment by GuyPardon** [comment]
Well then we can't really know without going through your detailed config and the log files. Are you open to considering a free trial of our commercial distro?

**Comment by wengchi0816** [comment]
I use version 4.0.6 and also encountered the same problem.
Upgrade to version 5.0, the same problem occurs.

Operating environment:
spring 4.2 + sqlServer 2016 + sqljdbc42.jar + tomcat 8.5

**Comment by wengchi0816** [comment]
> **Describe the bug**
> We use atomikos to manage 2 databases.
> We have randomly having error
> "The function COMMIT: failed. The status is: -4. Error: "*** SQLJDBC_XA DTC_ERROR Context: xa_commit, state=1, StatusCode:-4 (0xFFFFFFFC) ***"
> 
> while I am not searching the root cause of this exception, the issue is that the Atomikos is not throwning any exception to Spring. This is a duplicate of bug #70 but on the 4.0.6
> 
> What is the expected behavior we should have ?
> 
> Thanks

I updated sqljdbc_xa.dll to version 8.2.2 and it solved the problem

**Comment by GuyPardon** [comment]
Thanks for the feedback!

**Comment by GuyPardon** [comment]
The exception is "hidden" because it means the Xid no longer exists in the SQLServer. This happens if a first commit attempt seemed to fail (but it worked and the ack was lost over the network) and we retry.
