### ISSUE TITLE
Unable to enable exclusive connections

### ISSUE THREAD

**Issue by marcusportmann** [atomikos/transactions-essentials#95]
Hello,

I am experiencing an issue when using Atomikos with Hibernate and H2 as a result of the transaction interleaving implemented by Atomikos, which is not supported by H2. 

What appears to be happening is that an existing connection that is already associated with a different transaction context is re-used, which results in an exception similar to the following:

2019-09-25 11:56:38.461  WARN   --- [           main] c.a.datasource.xa.XAResourceTransaction  : XA resource 'main-ApplicationDataSource': resume for XID 'XID: 31302E33372E3132392E3133342E746D313536393430353339323635313030303035:31302E33372E3132392E3133342E746D35' raised -4: the supplied XID is invalid for this XA resource

I believe this is the same problem referenced here: https://fogbugz.atomikos.com/default058e.html?community.6.2177.4

I found the following page on the Atomikos website, which appears to say that exclusive transactions are required: https://www.atomikos.com/Documentation/ExternalConnectionPool

Is it possible to provide the capability to enable exclusive connections in Atomikos Essentials? If this capability does already exist is it possible to get it documented?

Kind regards,

Marcus Portmann

**Comment by GuyPardon** [comment]
Hi Marcus,

Thanks - this functionality is available in our commercial release. It's not free, but we do have a free trial if you're interested.

Guy
