### ISSUE TITLE
Getting Error - after upgrade to Atomikos 5.0.1-  There is no registered resource that can recover the given XAResource instance. 

### ISSUE THREAD

**Issue by TapasBhattacharjeefis** [atomikos/transactions-essentials#96]
I have integrated atomikos with spring and dbcp2 datasources. It was working fine with Atomikos 4.0.6 but had memory leak issues with TemporaryXATransactionalResource. I thought after upgrade it would reduce memory leaks but it fails with following error - Caused by: javax.transaction.SystemException: There is no registered resource that can recover the given XAResource instance. 
Please register a corresponding resource first.
	at com.atomikos.icatch.jta.TransactionImp.enlistResource(TransactionImp.java:277)
	at org.apache.commons.dbcp2.managed.TransactionContext.setSharedConnection(TransactionContext.java:94)

The Spring bean definition looks like - 
<bean id="fuelsTxDataSource" class="org.apache.commons.dbcp2.managed.BasicManagedDataSource">
			<property name="driverClassName" value="oracle.jdbc.driver.OracleDriver"/>
	      	<property name="url" value="jdbc:oracle:thin:@10.249.88.218:1521:SHELLUK"/>
	      	<property name="username" value="NUCDBA"/>
	      	<property name="password" value="NUCDBA"/>
			<property name="initialSize"><value>10</value></property>
			<property name="maxTotal"><value>300</value></property>
			<property name="accessToUnderlyingConnectionAllowed"><value>true</value></property>
			<property name="jmxName" value="org.apache.dbcp:DataSource=fuel"/>
			<property name="validationQuery"><value>SELECT * from dual</value></property>
			<property name="transactionManager" ref="transactionManager"/>
			<property name="testOnBorrow"><value>true</value></property>
			<property name="logAbandoned"><value>true</value></property>
			<property name="removeAbandonedOnBorrow"><value>true</value></property>
			<property name="removeAbandonedTimeout"><value>30</value></property>
		</bean>
		<bean id="transactionManager" class="com.atomikos.icatch.jta.UserTransactionManager" init-method="init" destroy-method="close"> 
 	  		 
   			<property name="forceShutdown" value="false" /> 
		</bean> 
		
		<bean id="transactionManagerWrapper" class="org.springframework.transaction.jta.JtaTransactionManager"> 
   			<property name="transactionManager" ref="transactionManager" /> 
   			<property name="userTransaction" ref="userTransaction" /> 
		</bean>
		
		<bean id="userTransaction" class="com.atomikos.icatch.jta.UserTransactionImp"> 
			
			<property name="transactionTimeout" value="1000" /> 
		</bean>
The DBCP2 version - commons-dbcp2-2.1.1.jar
Atomikos - 5.0.1
Spring version - 4.2.0

Is here any configuration sample to provide TransactionRecoverableResource?

**Comment by GuyPardon** [comment]
We don't have a sample - we only have samples for the common use cases whereas it seems you are using a 3rd party datasource with explicit JTA/XA enlistment.
