### ISSUE TITLE
com.atomikos.datasource.ResourceException: XA resource raised -3: the XA resource detected an internal error

### ISSUE THREAD

**Issue by wmdeepsea** [atomikos/transactions-essentials#97]
**Describe the bug**

**To Reproduce**

 1. What you were doing (or trying to do)
 1. What happened
 1. What you expected to happen instead
 1. What TransactionsEssentials version you are using

**Additional context**

_I understand that this project is not intended for support - because bug reports may or may not be considered for inclusion some day (in a future release). If this is issue is important to me then I can go to https://www.atomikos.com/Main/SupportOverview and arrange a paid support subscription._

**Comment by GuyPardon** [comment]
Any details? :-)

**Comment by saikris12** [comment]
Hi..We are seeing the same issue in our application. 

The exception in the logs : 2019-11-06T17:52:05,955  WARN  [XAResourceTransaction, DefaultMessageListenerContainer-1] XA resource 'CustomerAtomikosDataSource': resume for XID 'XID: 3137322E31392E302E322E746D313537333036323732353432363035383530:3137322E31392E302E322E746D313730' **raised -3: the XA resource detected an internal error**
oracle.jdbc.xa.OracleXAException: null
	at oracle.jdbc.xa.OracleXAResource.checkError(OracleXAResource.java:1110) ~[ojdbc14-11.2.0.3.0.jar!/:11.2.0.3.0]
	at oracle.jdbc.xa.client.OracleXAResource.start(OracleXAResource.java:240) ~[ojdbc14-11.2.0.3.0.jar!/:11.2.0.3.0]
at com.atomikos.util.DynamicProxySupport.invoke(DynamicProxySupport.java:116) [atomikos-util-5.0.3.jar!/:?]
	at com.sun.proxy.$Proxy224.prepareStatement(Unknown Source) [?:?]
2019-11-06T17:52:06,007  WARN  [AtomikosJdbcConnectionProxy, DefaultMessageListenerContainer-1] **Error enlisting in transaction - connection might be broken? Please check the logs for more information**...

We randomly see this warning in the logs. Not really sure what is causing this. Below is our atomikos configuration. We use transaction to commit to DB and write to a local embedded Active MQ. 

`<bean id="atomikosTransactionManager" class="com.atomikos.icatch.jta.UserTransactionManager"
          init-method="init" destroy-method="close" depends-on="userTransactionService">
        <property name="forceShutdown" value="false" />
        <property name="startupTransactionService" value="false" />
    </bean>

    <bean id="userTransactionService" class="com.atomikos.icatch.config.UserTransactionServiceImp"
          init-method="init" destroy-method="shutdownWait">
        <constructor-arg>
            <props>
                <prop key="com.atomikos.icatch.service">com.atomikos.icatch.standalone.UserTransactionServiceFactory</prop>
                <prop key="com.atomikos.icatch.output_dir">logs</prop>
                <prop key="com.atomikos.icatch.log_base_dir">logs</prop>
                <prop key="com.atomikos.icatch.force_shutdown_on_vm_exit">true</prop>
                <prop key="com.atomikos.icatch.default_jta_timeout">60000</prop>
                <prop key="com.atomikos.icatch.max_timeout">300000</prop>
                <prop key="com.atomikos.icatch.max_actives">100</prop>
            </props>
        </constructor-arg>
    </bean>

    <bean id="atomikosUserTransaction"
          class="com.atomikos.icatch.jta.J2eeUserTransaction">
    </bean>

    <bean id="transactionManager" class="org.springframework.transaction.jta.JtaTransactionManager"
          depends-on="atomikosTransactionManager,atomikosUserTransaction">
        <property name="transactionManager" ref="atomikosTransactionManager" />
        <property name="userTransaction" ref="atomikosUserTransaction" />
        <property name="allowCustomIsolationLevels" value="true"/>
    </bean>

    <bean id="JtaPlatformInitializer" class="org.springframework.beans.factory.config.MethodInvokingBean">
        <property name="targetClass" value="ca.interac.etransfer.notification.config.AtomikosJtaPlatform" />
        <property name="targetMethod" value="factoryInit" />
        <property name="arguments">
            <list>
                <ref bean="atomikosTransactionManager" />
                <ref bean="atomikosUserTransaction" />
            </list>
        </property>
    </bean>

    <bean id="atomikosJmsConnectionFactory" primary="true" class="com.atomikos.jms.AtomikosConnectionFactoryBean"
          init-method="init" destroy-method="close">
        <property name="uniqueResourceName" value="ActiveMQXA" />
        <property name="xaConnectionFactory" ref="xaAMQConnectionFactory"/>
        <property name="minPoolSize" value="15" />
        <property name="maxPoolSize" value="100" />
    </bean>

    <bean id="xaAMQConnectionFactory" class="org.apache.activemq.ActiveMQXAConnectionFactory">
        <property name="brokerURL" value="vm://embedded?broker.persistent=false,useShutdownHook=false" />
    </bean>

    <bean id="jmsTemplate" class="org.springframework.jms.core.JmsTemplate">
        <property name="connectionFactory" ref="atomikosJmsConnectionFactory" />
        <property name="receiveTimeout" value="2000" />
        <property name="sessionTransacted" value="true" />
        <property name="sessionAcknowledgeMode" value="1" />
    </bean>

    <bean id="jmsEventListenerContainerFactory" class="org.springframework.jms.config.DefaultJmsListenerContainerFactory">
        <property name="connectionFactory" ref="xaAMQConnectionFactory"/>
        <property name="concurrency" value="20-100" />
        <property name="transactionManager" ref="transactionManager"/>
        <property name="sessionAcknowledgeMode" value="1"/>
        <property name="sessionTransacted" value="true" />
    </bean>
<bean id="customerXaDS" name="customerXaDS" class="oracle.jdbc.xa.client.OracleXADataSource">
        <property name="URL" value="${customer.database.url}"/>
        <property name="user" value="${customer.database.username}"/>
        <property name="password" value="${customer.database.password}"/>
    </bean>

    <bean id="dataSource" primary="true" name="customerDataSource" class="com.atomikos.jdbc.AtomikosDataSourceBean"
          init-method="init" destroy-method="close">
        <property name="uniqueResourceName" value="CustomerAtomikosDataSource"/>
        <property name="xaDataSourceClassName" value="oracle.jdbc.xa.OracleXADataSource"/>
        <property name="xaDataSource" ref="customerXaDS"/>
        <property name="minPoolSize" value="5" />
        <property name="maxPoolSize" value="100" />
        <property name="maxLifetime" value="60"/>
        <property name="localTransactionMode" value="true" />

    </bean>

    <bean id="customerEntityManagerFactory" primary="true" class="org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean"
          depends-on="transactionManager,JtaPlatformInitializer">
        <property name="jtaDataSource" ref="dataSource"/>
        <property name="jpaVendorAdapter">
            <bean class="org.springframework.orm.jpa.vendor.HibernateJpaVendorAdapter">
                <property name="showSql" value="false" />
            </bean>
        </property>
        <property name="packagesToScan" value="com.example"/>
        <property name="persistenceUnitName" value="customerPersistenceUnit"/>
        <property name="jpaProperties">
            <value>
                hibernate.connection.driver_class=oracle.jdbc.driver.OracleDriver
                hibernate.dialect=org.hibernate.dialect.Oracle10gDialect
                hibernate.current_session_context_class=jta
                hibernate.transaction.manager_lookup_class=com.atomikos.icatch.jta.hibernate3.TransactionManagerLookup
                hibernate.transaction.jta.platform=com.example.AtomikosJtaPlatform
                hibernate.transaction.factory_class=org.hibernate.engine.transaction.internal.jta.CMTTransactionFactory
                hibernate.cache.region.factory_class=org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
                hibernate.cache.use_second_level_cache=true
                hibernate.cache.use_query_cache=true
                hibernate.generate_statistics=true
                hibernate.generate_statistics=true
                hibernate.temp.use_jdbc_metadata_defaults=false
            </value>
        </property>
    </bean>`

So we write to the database (Oracle 19c) and publish to the queue (In-memory embedded Active MQ). The listener consumes the message from the queue and processes the message. The error happens when the app was trying to execute a select query after picking the message from the queue. As mentioned before it does not happen everytime and occurs randomly. We are using atomikos transaction essentials 5.0.3. Any help is highly appreciated.

**Comment by GuyPardon** [comment]
OK thanks!

This would require some extensive log analysis to diagnose. Are you open to a free trial of our commercial offering so we can have a look at this?

**Comment by saikris12** [comment]
@GuyPardon We are currently working on an interim solution that requires JTA within a spring boot application. I am not sure if the company is going to use this solution in the future, but we can definitely try to troubleshoot this issue with the free trial. I would like to discuss in detail about the issue and my findings in the past few days. Please let me the know the appropriate channel to contact.

**Comment by GuyPardon** [comment]
Hi,

Thanks - please check here for how to proceed:

https://www.atomikos.com/Main/ExtremeTransactionsFreeTrial

Guy

**Comment by wmdeepsea** [comment]
The problem is resolved, because my Oracle DB didn't install JAVA_XA package.

**Comment by GuyPardon** [comment]
OK thanks for the update!
